

trigger:
- main

pool:
  name: DevProdQApool


steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'EnvironmentDevProdQA'
      backendAzureRmStorageAccountName: 'gaurav85strg'
      backendAzureRmContainerName: 'gaurav85container'
      backendAzureRmKey: 'Terraformtfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'EnvironmentDevProdQA'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'EnvironmentDevProdQA'
