

trigger:
- main

pool:
  name: DevProdQApool


steps:
  - task: TerraformTask@5
    displayName: terraform init  
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
      backendServiceArm: 'EnvironmentDevProdQA'
      backendAzureRmStorageAccountName: 'gaurav85strg'
      backendAzureRmContainerName: 'gaurav85container'
      backendAzureRmKey: 'Terraformtfstate'

  - task: TerraformTask@5
    displayName: terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
    environmentServiceNameAzureRM: 'EnvironmentDevProdQA'
      environmentServiceNameAzureRM: 'EnvironmentDevProdQA'

  - task: TerraformTask@5
    displayName: terraform apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
      environmentServiceNameAzureRM: 'EnvironmentDevProdQA'
  - task: TerraformTask@5
    displayName: terraform destroy
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
      environmentServiceNameAzureRM: 'EnvironmentDevProdQA'
